import os
from supabase_py import create_client, Client
from dotenv import load_dotenv
import asyncio
import pandas as pd
from tqdm import tqdm
import psycopg2

load_dotenv()
# Environment variables
url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
connection_string = os.environ.get("CONNECTION_STRING")

# Create a Supabase client
supabase: Client = create_client(url, key)


def get_all_data(table_name: str):
    data = supabase.table(table_name).select("*").execute()
    return data

async def create_table_from_CSV(csv_path: str, table_name: str):
    df = pd.read_csv(csv_path)
    # query = """
    # CREATE TABLE IF NOT EXISTS your_table (
    #     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    #     name TEXT NOT NULL,
    #     age INT
    # );
    # """
    schema = pd.io.sql.get_schema(df, table_name)
    query = f"""{schema}"""

    try:
        # Using REST API for raw SQL
        result = await supabase.postgrest.rpc(
            'exec',  # This is a custom PostgreSQL function you need to create first
            {'query': query}
        ).execute()
        print("Table created successfully")
        return result
    except Exception as e:
        print("Error creating table:", e)
        raise e


def dataFrametoSupabase(
    df: pd.DataFrame, table_name: str
):
    try:
        results = []
        # rows = [row for _, row in df.iterrows()]
        for _, row in tqdm(df.iterrows(), total=df.shape[0]):
            data = row.to_dict()
            result = supabase.table(table_name).insert(data).execute()
            results.append(result)
        print(f"{len(results)} inserted successfully")
        return results
    except Exception as e:
        print(f"Error inserting data: {str(e)}")
        raise e

#insert data from CSV to Supabase
def insert_data_from_CSV(csv_path: str):
    df = pd.read_csv(csv_path)
    data =df.to_dict(orient='records')

    try:
        supabase.table("BDC_Info").insert(data).execute()
        print("Data inserted successfully")
    except Exception as e:
        print("Error inserting data:", e)
        raise e


def copy_data_to_postgres(csv_path: str):
    # Establish connection
    conn = psycopg2.connect(connection_string)

    #print(conn.get_dsn_parameters(), "\n")

    # Create a cursor object
    cur = conn.cursor()

    try:
        # Execute a query
        with open(csv_path, 'r') as file:
            sql = "COPY bdc_info_2 FROM STDIN WITH CSV HEADER DELIMITER AS ','"
            cur.copy_expert(sql, file)

        # Commit the transaction
        conn.commit()

        # Verify data was inserted
        cur.execute("SELECT COUNT(*) FROM bdc_info_2")
        count = cur.fetchone()[0]
        print(f"Successfully inserted {count} rows")

        return True

    except psycopg2.Error as e:
        print("Error connecting to PostgreSQL:", e)
        conn.rollback()
        return False

    finally:
        # Close cursor and connection
        if 'cur' in locals():
            cur.close()
        if 'conn' in locals():
            conn.close()

csv_path = "exports/bdc_01_GSOSatellite_fixed_broadband_D23_14may2024.csv"
csv_path2 = "exports/bdc_01_LBRFixedWireless_fixed_broadband_D23_14may2024.csv"
#df = pd.read_csv(csv_path, encoding="utf-8")

print(copy_data_to_postgres(csv_path))
